### ISSUE TITLE
Link for news post ISPCS paper does not work

### ISSUE THREAD

**Issue by michielp1807** [trifectatechfoundation/trifectatech-website#17]
The link for the new post about David's ISPCS paper does not work. As seen [here](https://github.com/trifectatechfoundation/trifectatech-website/blob/b8ded1ac2b15b5cba4db9bb69ee4f9723107f9f9/templates/news.html#L15) and [here](https://github.com/trifectatechfoundation/trifectatech-website/blob/b8ded1ac2b15b5cba4db9bb69ee4f9723107f9f9/templates/initiatives/time-synchronization.html#L73), the link seems to be set to the title of the news post? I'm guessing it should link to the [blogpost on Tweede golf's website](https://tweedegolf.nl/en/blog/138/ispcs-paper-estimating-noise-for-clock-synchronizing-kalman-filters) instead.

**Comment by erikjee** [comment]
Thanks!

Fixed in https://github.com/trifectatechfoundation/trifectatech-website/commit/7073726abd5842aca54eec3407b2bfccaa105f68
